package singleton;

import model.Referral;
import java.io.*;
import java.time.LocalDateTime;

public class ReferralManager {
    // 1. Static instance
    private static ReferralManager instance;

    // 2. Private constructor
    private ReferralManager() {}

    // 3. Public accessor
    public static synchronized ReferralManager getInstance() {
        if (instance == null) {
            instance = new ReferralManager();
        }
        return instance;
    }

    // Logic to simulate sending an email/processing
    public void processReferral(Referral r) {
        System.out.println("Singleton: Processing referral " + r.getId());
        generateReferralLetter(r);
    }

    private void generateReferralLetter(Referral r) {
        String filename = "Referral_Letter_" + r.getId() + ".txt";
        try (PrintWriter writer = new PrintWriter(new FileWriter(filename))) {
            writer.println("=== NHS REFERRAL LETTER ===");
            writer.println("Date: " + LocalDateTime.now());
            writer.println("Referral ID: " + r.getId());
            writer.println("Patient ID: " + r.getPatientId());
            writer.println("Urgency: " + r.getUrgency());
            writer.println("---------------------------");
            writer.println("Clinical Summary:");
            writer.println(r.getSummary());
            writer.println("---------------------------");
            writer.println("Generated by ReferralManager Singleton System.");
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}